# Generated by Django 2.2.5 on 2019-09-12 05:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Peligro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_peligro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_area', to='ipercAPI.Area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_riesgo', models.CharField(max_length=30)),
                ('peligro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_peligro', to='ipercAPI.Peligro')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_area', to='ipercAPI.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Iperc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperc_area', to='ipercAPI.Area')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperc_labor', to='ipercAPI.Labor')),
                ('peligro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperc_peligro', to='ipercAPI.Peligro')),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperc_riesgo', to='ipercAPI.Riesgo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperc_usuario', to='ipercAPI.Usuario')),
            ],
        ),
    ]
