# Generated by Django 2.2.5 on 2019-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipercAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperc',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firma_digital'),
        ),
    ]
