# Generated by Django 2.2.5 on 2019-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipercAPI', '0002_iperc_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperc',
            name='foto_reporte',
            field=models.ImageField(blank=True, null=True, upload_to='foto_reporte'),
        ),
    ]
