# Generated by Django 2.2.5 on 2019-09-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipercAPI', '0003_iperc_foto_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iperc',
            name='codigo',
        ),
    ]
