# Generated by Django 2.2.5 on 2019-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipercAPI', '0004_remove_iperc_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperc',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
