# Generated by Django 2.2.5 on 2019-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipercAPI', '0005_iperc_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iperc',
            name='puntaje',
            field=models.IntegerField(),
        ),
    ]
