# Generated by Django 2.2.5 on 2019-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipercAPI', '0007_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
